export * from './home/home.page'
export * from './players/players.page'
export * from './teams/teams.page'
export * from './news/news.page'
export * from './fplayers/fplayers.page'
export * from './fteams/fteams.page'